name: Extract Libraries Data

on:
  schedule:
    - cron: '0 16 * * *'  # For summer time (CEST, 18:00 = 16:00 UTC)
    - cron: '0 17 * * *'  # For winter time (CET, 18:00 = 17:00 UTC)

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run extraction script
        env:
          GOLEMIO_API_KEY: ${{ secrets.GOLEMIO_API_KEY }}
        run: python extract_libraries.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add libraries.csv
          git commit -m "Update libraries data" || echo "No changes to commit"
          git push