name: Extract Libraries Data

on:
  schedule:
    - cron: '00 5 * * *'  # 21:50 UTC = 23:50 CEST
    - cron: '00 6 * * *'  # 22:50 UTC = 23:50 CET
  workflow_dispatch:  # Manual trigger

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pytz

      - name: Run extraction script
        env:
          GOLEMIO_API_KEY: ${{ secrets.GOLEMIO_API_KEY }}
        run: python extract_libraries.py

      - name: Check if CSV was created
        run: |
          if [ -f "libraries.csv" ]; then
            echo "libraries.csv was created successfully"
            ls -la libraries.csv
          else
            echo "libraries.csv was NOT created - script may have failed"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Check if libraries.csv exists before trying to add it
          if [ -f "libraries.csv" ]; then
            git add libraries.csv
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update libraries data - $(date '+%Y-%m-%d %H:%M')"
              git push
            fi
          else
            echo "libraries.csv does not exist, skipping commit"
            exit 1
          fi